/**
 * Seizn Auto-PR Fixer - PR Body Template
 *
 * Generates formatted PR descriptions for auto-fix PRs.
 */

import type {
  IssueDetection,
  FixSuggestion,
  PRMetadata,
  IssueSeverity,
} from '../types';

// ============================================
// Template Functions
// ============================================

/**
 * Generate PR title from suggestions
 */
export function generatePRTitle(suggestions: FixSuggestion[]): string {
  if (suggestions.length === 0) {
    return '[Auto-PR] RAG quality improvements';
  }

  if (suggestions.length === 1) {
    return `[Auto-PR] ${suggestions[0].title}`;
  }

  // Group by type
  const types = new Set(suggestions.map(s => s.type));
  const typeLabels: Record<string, string> = {
    chunking_strategy: 'chunking',
    metadata_enrichment: 'metadata',
    prompt_tuning: 'prompt',
    reindex: 'indexing',
    embedding_update: 'embedding',
    retrieval_config: 'retrieval',
    answer_contract: 'validation',
    cache_invalidation: 'cache',
    source_update: 'sources',
    model_switch: 'model',
  };

  const labels = Array.from(types).map(t => typeLabels[t] || t).slice(0, 3);

  return `[Auto-PR] Fix ${suggestions.length} issues: ${labels.join(', ')}`;
}

/**
 * Generate branch name from suggestions
 */
export function generateBranchName(
  prefix: string,
  suggestions: FixSuggestion[]
): string {
  const timestamp = Date.now().toString(36);
  const type = suggestions[0]?.type || 'fix';

  return `${prefix}${type}-${timestamp}`;
}

/**
 * Generate commit message
 */
export function generateCommitMessage(suggestions: FixSuggestion[]): string {
  const lines = [
    'fix(rag): auto-fix RAG quality issues',
    '',
    'Applied fixes:',
    ...suggestions.map(s => `- ${s.title}`),
    '',
    'Generated by Seizn Auto-PR Fixer',
  ];

  return lines.join('\n');
}

/**
 * Generate full PR body
 */
export function generatePRBody(
  issues: IssueDetection[],
  suggestions: FixSuggestion[],
  metadata: PRMetadata
): string {
  const sections: string[] = [];

  // Header
  sections.push(`## RAG Quality Auto-Fix

This PR was automatically generated by **Seizn Auto-PR Fixer** to address detected RAG quality issues.

> **Trace ID:** \`${metadata.traceId}\`
> **Confidence:** ${(metadata.confidence * 100).toFixed(0)}%
> **Generated:** ${new Date(metadata.createdAt).toISOString()}
`);

  // Summary section
  sections.push(`### Summary

| Metric | Value |
|--------|-------|
| Issues Detected | ${metadata.summary.totalIssues} |
| Fixes Applied | ${metadata.summary.totalFixes} |
| Code Changes | ${metadata.summary.codeChanges} |
| Config Changes | ${metadata.summary.configChanges} |
`);

  // Issues section
  if (issues.length > 0) {
    sections.push(`### Detected Issues

${issues.map(issue => formatIssue(issue)).join('\n\n')}
`);
  }

  // Fixes section
  if (suggestions.length > 0) {
    sections.push(`### Applied Fixes

${suggestions.map((s, i) => formatSuggestion(s, i + 1)).join('\n\n')}
`);
  }

  // Impact section
  sections.push(generateImpactSection(suggestions));

  // Code changes section
  const codeChanges = suggestions.flatMap(s => s.codePatches || []);
  if (codeChanges.length > 0) {
    sections.push(`### Code Changes

${codeChanges.map(change => `
<details>
<summary><code>${change.filePath}</code> (${change.action})</summary>

\`\`\`
${change.description}
\`\`\`

</details>
`).join('\n')}
`);
  }

  // Config changes section
  const configChanges = suggestions.flatMap(s => s.configPatches || []);
  if (configChanges.length > 0) {
    sections.push(`### Configuration Changes

| Key | Current | New | Scope |
|-----|---------|-----|-------|
${configChanges.map(c => `| \`${c.key}\` | ${formatValue(c.currentValue)} | ${formatValue(c.newValue)} | ${c.scope} |`).join('\n')}
`);
  }

  // Testing section
  sections.push(`### Testing Checklist

- [ ] Review code changes for correctness
- [ ] Verify configuration changes are appropriate
- [ ] Run test suite to ensure no regressions
- [ ] Test with sample queries affected by the issues
- [ ] Monitor metrics after deployment
`);

  // Footer
  sections.push(`---

<details>
<summary>Metadata</summary>

\`\`\`json
${JSON.stringify(metadata, null, 2)}
\`\`\`

</details>

---

*This PR was generated automatically by [Seizn Auto-PR Fixer](https://www.seizn.com/docs/auto-pr)*
*Review the changes carefully before merging.*
`);

  return sections.join('\n');
}

// ============================================
// Helper Functions
// ============================================

function formatIssue(issue: IssueDetection): string {
  const severityEmoji = getSeverityEmoji(issue.severity);
  const confidenceBar = getConfidenceBar(issue.confidence);

  return `#### ${severityEmoji} ${issue.title}

**Severity:** ${issue.severity.toUpperCase()} | **Confidence:** ${confidenceBar} ${(issue.confidence * 100).toFixed(0)}%

${issue.description}

<details>
<summary>Evidence</summary>

${issue.evidence.map(e => `- **${e.type}:** ${e.description}`).join('\n')}

</details>
`;
}

function formatSuggestion(suggestion: FixSuggestion, index: number): string {
  const riskEmoji = getRiskEmoji(suggestion.impact.risk);

  return `#### ${index}. ${suggestion.title}

**Type:** ${suggestion.type} | **Effort:** ${suggestion.effort} | **Risk:** ${riskEmoji} ${suggestion.impact.risk}

${suggestion.description}

**Rationale:** ${suggestion.rationale}

**Expected Improvement:** ${suggestion.impact.expectedImprovement}
`;
}

function generateImpactSection(suggestions: FixSuggestion[]): string {
  // Calculate total impact
  const totalLatencyImpact = suggestions.reduce(
    (sum, s) => sum + (s.impact.latencyImpactMs || 0),
    0
  );
  const totalCostImpact = suggestions.reduce(
    (sum, s) => sum + (s.impact.costImpactPercent || 0),
    0
  );
  const allSideEffects = [...new Set(suggestions.flatMap(s => s.impact.sideEffects))];
  const affectedAreas = [...new Set(suggestions.flatMap(s => s.impact.affectedAreas))];

  return `### Impact Assessment

| Aspect | Impact |
|--------|--------|
| Affected Areas | ${affectedAreas.join(', ')} |
| Estimated Latency Change | ${totalLatencyImpact > 0 ? '+' : ''}${totalLatencyImpact}ms |
| Estimated Cost Change | ${totalCostImpact > 0 ? '+' : ''}${totalCostImpact}% |

${allSideEffects.length > 0 ? `
**Potential Side Effects:**
${allSideEffects.map(e => `- ${e}`).join('\n')}
` : ''}
`;
}

function getSeverityEmoji(severity: IssueSeverity): string {
  const emojis: Record<IssueSeverity, string> = {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🟢',
  };
  return emojis[severity];
}

function getRiskEmoji(risk: string): string {
  const emojis: Record<string, string> = {
    low: '🟢',
    medium: '🟡',
    high: '🔴',
  };
  return emojis[risk] || '⚪';
}

function getConfidenceBar(confidence: number): string {
  const filled = Math.round(confidence * 5);
  const empty = 5 - filled;
  return '█'.repeat(filled) + '░'.repeat(empty);
}

function formatValue(value: unknown): string {
  if (value === null || value === undefined) return '`null`';
  if (typeof value === 'string') return `\`"${value}"\``;
  if (typeof value === 'boolean') return value ? '`true`' : '`false`';
  if (typeof value === 'number') return `\`${value}\``;
  return `\`${JSON.stringify(value)}\``;
}

// ============================================
// Export Templates Object
// ============================================

export const PRTemplates = {
  generatePRTitle,
  generateBranchName,
  generateCommitMessage,
  generatePRBody,
};

export default PRTemplates;
