apiVersion: v1
kind: Service
metadata:
  name: {{ include "seizn.fullname" . }}
  labels:
    {{- include "seizn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.seizn.service.type }}
  ports:
    - port: {{ .Values.seizn.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "seizn.selectorLabels" . | nindent 4 }}
