/**
 * Seizn Autopilot PR Bot - PR Generator
 *
 * Generates PR titles, bodies, and context from analysis results.
 */

import { randomUUID } from 'crypto';
import type {
  TraceAnalysis,
  FixSuggestion,
  PRContext,
  PRFile,
  PRMetadata,
  AutopilotConfig,
  DetectedFailure,
  CodeChange,
  ConfigChange,
} from './types';

// ============================================
// Constants
// ============================================

const AUTOPILOT_VERSION = '1.0.0';

const SEVERITY_LABELS: Record<number, string> = {
  10: 'critical',
  9: 'critical',
  8: 'high',
  7: 'high',
  6: 'medium',
  5: 'medium',
  4: 'low',
  3: 'low',
  2: 'trivial',
  1: 'trivial',
};

const FIX_TYPE_EMOJI: Record<string, string> = {
  code: '',
  config: '',
  infrastructure: '',
  process: '',
};

// ============================================
// PR Generator Class
// ============================================

export class PRGenerator {
  private config: AutopilotConfig;

  constructor(config: AutopilotConfig) {
    this.config = config;
  }

  /**
   * Generate PR context from analysis and suggestions
   */
  generate(
    analysis: TraceAnalysis,
    suggestions: FixSuggestion[]
  ): PRContext {
    const filteredSuggestions = suggestions.filter(
      (s) => s.confidence >= this.config.minConfidence
    );

    if (filteredSuggestions.length === 0) {
      throw new Error('No suggestions meet the minimum confidence threshold');
    }

    const title = this.generateTitle(analysis, filteredSuggestions);
    const body = this.generateBody(analysis, filteredSuggestions);
    const files = this.generateFiles(filteredSuggestions);
    const headBranch = this.generateBranchName(analysis);
    const metadata = this.generateMetadata(analysis, filteredSuggestions);

    // Determine if PR should be draft based on suggestions
    const highRiskSuggestions = filteredSuggestions.filter(
      (s) => s.impact.risk === 'high' || s.requiresReview
    );
    const draft = highRiskSuggestions.length > 0;

    return {
      title,
      body,
      headBranch,
      baseBranch: this.config.baseBranch,
      files,
      reviewers: this.config.defaultReviewers,
      labels: this.generateLabels(analysis, filteredSuggestions),
      draft,
      analysis,
      suggestions: filteredSuggestions,
      metadata,
    };
  }

  /**
   * Generate PR title
   */
  private generateTitle(
    analysis: TraceAnalysis,
    suggestions: FixSuggestion[]
  ): string {
    const primaryFailure = analysis.failures[0];
    const primarySuggestion = suggestions[0];

    // Short, descriptive title
    const failureType = primaryFailure?.type || 'issue';
    const action = primarySuggestion?.title || 'fix';

    // Format: [autopilot] fix: <action> for <failure type>
    return `[autopilot] fix: ${action.toLowerCase()} for ${failureType.replace(/_/g, ' ')}`;
  }

  /**
   * Generate PR body (markdown)
   */
  private generateBody(
    analysis: TraceAnalysis,
    suggestions: FixSuggestion[]
  ): string {
    const sections: string[] = [];

    // Header
    sections.push('## Autopilot Fix');
    sections.push('');
    sections.push('This PR was automatically generated by Seizn Autopilot based on detected issues in production traces.');
    sections.push('');

    // Summary
    sections.push('### Summary');
    sections.push('');
    sections.push(`- **Trace ID:** \`${analysis.traceId}\``);
    sections.push(`- **Detected Failures:** ${analysis.failures.length}`);
    sections.push(`- **Severity:** ${analysis.severity}/10 (${SEVERITY_LABELS[analysis.severity] || 'unknown'})`);
    sections.push(`- **Confidence:** ${(analysis.confidence * 100).toFixed(1)}%`);
    sections.push('');

    // Failures
    sections.push('### Detected Issues');
    sections.push('');
    for (const failure of analysis.failures) {
      sections.push(`#### ${failure.type.replace(/_/g, ' ').toUpperCase()}`);
      sections.push('');
      sections.push(`> ${failure.message}`);
      sections.push('');
      sections.push('**Evidence:**');
      for (const evidence of failure.evidence) {
        sections.push(`- \`${evidence.path}\`: ${evidence.description}`);
      }
      sections.push('');
    }

    // Root Cause
    if (analysis.rootCause) {
      sections.push('### Root Cause Analysis');
      sections.push('');
      sections.push(`**Primary Cause:** ${analysis.rootCause.primary}`);
      sections.push('');
      if (analysis.rootCause.factors.length > 0) {
        sections.push('**Contributing Factors:**');
        for (const factor of analysis.rootCause.factors) {
          sections.push(`- ${factor}`);
        }
        sections.push('');
      }
    }

    // Fixes
    sections.push('### Applied Fixes');
    sections.push('');
    for (const suggestion of suggestions) {
      const emoji = FIX_TYPE_EMOJI[suggestion.type] || '';
      sections.push(`#### ${emoji} ${suggestion.title}`);
      sections.push('');
      sections.push(suggestion.description);
      sections.push('');
      sections.push(`- **Type:** ${suggestion.type}`);
      sections.push(`- **Strategy:** ${suggestion.strategy.replace(/_/g, ' ')}`);
      sections.push(`- **Confidence:** ${(suggestion.confidence * 100).toFixed(1)}%`);
      sections.push(`- **Risk:** ${suggestion.impact.risk}`);
      sections.push(`- **Effort:** ${suggestion.effort}`);
      sections.push('');

      // Code changes
      if (suggestion.codeChanges && suggestion.codeChanges.length > 0) {
        sections.push('**Code Changes:**');
        for (const change of suggestion.codeChanges) {
          sections.push(`- \`${change.filePath}\`: ${change.description}`);
        }
        sections.push('');
      }

      // Config changes
      if (suggestion.configChanges && suggestion.configChanges.length > 0) {
        sections.push('**Configuration Changes:**');
        for (const change of suggestion.configChanges) {
          sections.push(`- \`${change.key}\`: ${JSON.stringify(change.currentValue)} -> ${JSON.stringify(change.newValue)}`);
          sections.push(`  - ${change.description}`);
        }
        sections.push('');
      }

      // Impact
      sections.push('**Impact:**');
      sections.push(`- Expected improvement: ${suggestion.impact.improvement}`);
      if (suggestion.impact.sideEffects.length > 0) {
        sections.push('- Potential side effects:');
        for (const effect of suggestion.impact.sideEffects) {
          sections.push(`  - ${effect}`);
        }
      }
      sections.push('');
    }

    // Review checklist
    sections.push('### Review Checklist');
    sections.push('');
    sections.push('- [ ] Verify the fix addresses the root cause');
    sections.push('- [ ] Check for potential side effects');
    sections.push('- [ ] Ensure tests pass');
    sections.push('- [ ] Review configuration changes');
    sections.push('');

    // Footer
    sections.push('---');
    sections.push('');
    sections.push('*This PR was generated by [Seizn Autopilot](https://www.seizn.com/docs/autopilot). For questions or feedback, please contact the Seizn team.*');
    sections.push('');
    sections.push(`<sub>Autopilot Version: ${AUTOPILOT_VERSION} | Trace: ${analysis.traceId}</sub>`);

    return sections.join('\n');
  }

  /**
   * Generate files to include in PR
   */
  private generateFiles(suggestions: FixSuggestion[]): PRFile[] {
    const files: PRFile[] = [];
    const fileMap = new Map<string, PRFile>();

    for (const suggestion of suggestions) {
      // Process code changes
      if (suggestion.codeChanges) {
        for (const change of suggestion.codeChanges) {
          const existing = fileMap.get(change.filePath);
          if (existing) {
            // Merge changes (simple concat for now)
            existing.content += '\n' + change.newContent;
          } else {
            fileMap.set(change.filePath, {
              path: change.filePath,
              content: change.newContent,
              changeType: change.changeType,
              mode: '100644',
            });
          }
        }
      }

      // Process config changes (generate config file updates)
      if (suggestion.configChanges && suggestion.configChanges.length > 0) {
        const configFile = this.generateConfigFile(suggestion.configChanges);
        if (configFile) {
          fileMap.set(configFile.path, configFile);
        }
      }
    }

    return Array.from(fileMap.values());
  }

  /**
   * Generate config file from changes
   */
  private generateConfigFile(changes: ConfigChange[]): PRFile | null {
    if (changes.length === 0) return null;

    // Group by scope
    const byScope = new Map<string, ConfigChange[]>();
    for (const change of changes) {
      const existing = byScope.get(change.scope) || [];
      existing.push(change);
      byScope.set(change.scope, existing);
    }

    // Generate JSON config patch
    const config: Record<string, unknown> = {};
    for (const change of changes) {
      // Set nested value
      const parts = change.key.split('.');
      let current = config;
      for (let i = 0; i < parts.length - 1; i++) {
        if (!current[parts[i]]) {
          current[parts[i]] = {};
        }
        current = current[parts[i]] as Record<string, unknown>;
      }
      current[parts[parts.length - 1]] = change.newValue;
    }

    return {
      path: '.seizn/autopilot-config-patch.json',
      content: JSON.stringify(config, null, 2),
      changeType: 'create',
      mode: '100644',
    };
  }

  /**
   * Generate branch name
   */
  private generateBranchName(analysis: TraceAnalysis): string {
    const timestamp = new Date().toISOString().slice(0, 10).replace(/-/g, '');
    const traceShort = analysis.traceId.slice(0, 8);
    const failureType = analysis.failures[0]?.type || 'fix';

    return `${this.config.branchPrefix}${failureType}-${traceShort}-${timestamp}`;
  }

  /**
   * Generate labels for PR
   */
  private generateLabels(
    analysis: TraceAnalysis,
    suggestions: FixSuggestion[]
  ): string[] {
    const labels = [...this.config.labels];

    // Add severity label
    const severityLabel = SEVERITY_LABELS[analysis.severity];
    if (severityLabel) {
      labels.push(`severity:${severityLabel}`);
    }

    // Add type labels
    const types = new Set(suggestions.map((s) => s.type));
    for (const type of types) {
      labels.push(`type:${type}`);
    }

    // Add risk label
    const hasHighRisk = suggestions.some((s) => s.impact.risk === 'high');
    if (hasHighRisk) {
      labels.push('needs-review');
    }

    return [...new Set(labels)];
  }

  /**
   * Generate PR metadata
   */
  private generateMetadata(
    analysis: TraceAnalysis,
    suggestions: FixSuggestion[]
  ): PRMetadata {
    const repoFullName =
      this.config.owner && this.config.repo ? `${this.config.owner}/${this.config.repo}` : undefined;
    const codeChanges = suggestions.reduce(
      (sum, s) => sum + (s.codeChanges?.length || 0),
      0
    );
    const configChanges = suggestions.reduce(
      (sum, s) => sum + (s.configChanges?.length || 0),
      0
    );

    return {
      traceId: analysis.traceId,
      userId: analysis.userId,
      repoFullName,
      autopilotVersion: AUTOPILOT_VERSION,
      createdAt: new Date().toISOString(),
      confidence: analysis.confidence,
      fixSummary: {
        totalFixes: suggestions.length,
        codeChanges,
        configChanges,
      },
    };
  }

  /**
   * Generate commit message for the fix
   */
  generateCommitMessage(
    analysis: TraceAnalysis,
    suggestions: FixSuggestion[]
  ): string {
    const primaryFailure = analysis.failures[0];
    const primarySuggestion = suggestions[0];

    const subject = `fix(autopilot): ${primarySuggestion?.title.toLowerCase() || 'apply auto-fix'}`;
    const body = [
      '',
      `Addresses ${primaryFailure?.type.replace(/_/g, ' ')} detected in trace ${analysis.traceId}`,
      '',
      'Changes:',
      ...suggestions.map((s) => `- ${s.title}: ${s.description.slice(0, 80)}`),
      '',
      `Confidence: ${(analysis.confidence * 100).toFixed(1)}%`,
      `Severity: ${analysis.severity}/10`,
      '',
      'Generated by Seizn Autopilot',
    ];

    return subject + body.join('\n');
  }
}

// ============================================
// Factory Function
// ============================================

export function createPRGenerator(config: AutopilotConfig): PRGenerator {
  return new PRGenerator(config);
}
