import { NextRequest, NextResponse } from 'next/server';
import { createServerClient } from '@/lib/supabase';
import {
  authenticateRequest,
  isAuthError,
  authErrorResponse,
} from '@/lib/api-auth';

// Supported config formats
const CONFIG_FORMATS: Record<string, { file: string; tool: string; format: string }> = {
  claude: { file: 'CLAUDE.md', tool: 'Claude Code', format: 'markdown' },
  codex: { file: 'AGENTS.md', tool: 'OpenAI Codex CLI', format: 'markdown' },
  cursor: { file: '.cursor/rules', tool: 'Cursor', format: 'mdc' },
  cursorrules: { file: '.cursorrules', tool: 'Cursor (legacy)', format: 'plain' },
  windsurf: { file: '.windsurfrules', tool: 'Windsurf', format: 'plain' },
  copilot: { file: '.github/copilot-instructions.md', tool: 'GitHub Copilot', format: 'markdown' },
  cline: { file: '.clinerules', tool: 'Cline', format: 'plain' },
  aider: { file: 'CONVENTIONS.md', tool: 'Aider', format: 'markdown' },
};

function formatContent(
  instructions: string[],
  preferences: string[],
  facts: string[],
  formatId: string,
  project?: string,
): string {
  const timestamp = new Date().toISOString();
  const projectHeader = project ? ` - ${project}` : '';

  switch (formatId) {
    case 'claude':
    case 'copilot':
      return [
        `# Project Instructions${projectHeader}`,
        '',
        preferences.length ? `## Preferences\n${preferences.map(p => `- ${p}`).join('\n')}` : '',
        instructions.length ? `## Instructions\n${instructions.map(i => `- ${i}`).join('\n')}` : '',
        facts.length ? `## Key Facts\n${facts.map(f => `- ${f}`).join('\n')}` : '',
        '',
        '---',
        `*Auto-generated by Seizn Memory (seizn.com). Last synced: ${timestamp}*`,
      ].filter(Boolean).join('\n');

    case 'codex':
      return [
        `# AGENTS.md${projectHeader}`,
        '',
        '> This file was auto-generated by Seizn Memory.',
        '',
        preferences.length ? `## Preferences\n${preferences.map(p => `- ${p}`).join('\n')}` : '',
        instructions.length ? `## Instructions\n${instructions.map(i => `- ${i}`).join('\n')}` : '',
        facts.length ? `## Context\n${facts.map(f => `- ${f}`).join('\n')}` : '',
        '',
        `<!-- Seizn sync: ${timestamp} -->`,
      ].filter(Boolean).join('\n');

    case 'cursor':
    case 'cursorrules':
    case 'windsurf':
    case 'cline':
      return [
        `You are working on a project${projectHeader} with the following context:`,
        '',
        preferences.length ? `Preferences:\n${preferences.map(p => `- ${p}`).join('\n')}` : '',
        '',
        instructions.length ? `Follow these instructions:\n${instructions.map(i => `- ${i}`).join('\n')}` : '',
        '',
        facts.length ? `Key facts:\n${facts.map(f => `- ${f}`).join('\n')}` : '',
        '',
        `# Auto-generated by Seizn Memory (seizn.com). Last synced: ${timestamp}`,
      ].filter(Boolean).join('\n');

    case 'aider':
      return [
        `# Conventions${projectHeader}`,
        '',
        preferences.length ? `## Preferences\n${preferences.map(p => `- ${p}`).join('\n')}` : '',
        instructions.length ? `## Instructions\n${instructions.map(i => `- ${i}`).join('\n')}` : '',
        facts.length ? `## Context\n${facts.map(f => `- ${f}`).join('\n')}` : '',
        '',
        `<!-- Seizn sync: ${timestamp} -->`,
      ].filter(Boolean).join('\n');

    default:
      return instructions.concat(preferences, facts).join('\n');
  }
}

// POST /api/config-sync - Generate config content for a given format
export async function POST(request: NextRequest) {
  try {
    const authResult = await authenticateRequest(request, { skipUsageCheck: true });
    if (isAuthError(authResult)) {
      return authErrorResponse(authResult.authError);
    }

    const { userId } = authResult;
    const body = await request.json();
    const { format: formatId, project } = body as { format?: string; project?: string };

    if (!formatId || !CONFIG_FORMATS[formatId]) {
      return NextResponse.json(
        { error: `Invalid format. Available: ${Object.keys(CONFIG_FORMATS).join(', ')}` },
        { status: 400 },
      );
    }

    const supabase = createServerClient();

    // Query memories by type
    const [instrRes, prefRes, factRes] = await Promise.all([
      supabase
        .from('memories')
        .select('content')
        .eq('user_id', userId)
        .eq('memory_type', 'instruction')
        .eq('is_deleted', false)
        .order('created_at', { ascending: false })
        .limit(50),
      supabase
        .from('memories')
        .select('content')
        .eq('user_id', userId)
        .eq('memory_type', 'preference')
        .eq('is_deleted', false)
        .order('created_at', { ascending: false })
        .limit(50),
      supabase
        .from('memories')
        .select('content')
        .eq('user_id', userId)
        .eq('memory_type', 'fact')
        .eq('is_deleted', false)
        .order('created_at', { ascending: false })
        .limit(20),
    ]);

    const instructions = (instrRes.data || []).map(m => m.content);
    const preferences = (prefRes.data || []).map(m => m.content);
    const facts = (factRes.data || []).map(m => m.content);

    const content = formatContent(instructions, preferences, facts, formatId, project);
    const fmt = CONFIG_FORMATS[formatId];

    return NextResponse.json({
      success: true,
      content,
      filename: fmt.file,
      format: fmt.format,
      tool: fmt.tool,
      memoryCounts: {
        instructions: instructions.length,
        preferences: preferences.length,
        facts: facts.length,
      },
    });
  } catch (error) {
    console.error('Config sync error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

// GET /api/config-sync - List available formats
export async function GET() {
  return NextResponse.json({
    formats: Object.entries(CONFIG_FORMATS).map(([id, fmt]) => ({
      id,
      ...fmt,
    })),
  });
}
