import { beforeEach, describe, expect, it, vi } from 'vitest';
import { NextRequest } from 'next/server';

const authenticateRequestMock = vi.fn();
const isAuthErrorMock = vi.fn();
const authErrorResponseMock = vi.fn();
const logRequestMock = vi.fn();

const createServerClientMock = vi.fn();
const createMemoryV3ServiceMock = vi.fn();
const getEdgesMock = vi.fn();
const listNotesMock = vi.fn();

vi.mock('@/lib/api-auth', () => ({
  authenticateRequest: authenticateRequestMock,
  isAuthError: isAuthErrorMock,
  authErrorResponse: authErrorResponseMock,
  logRequest: logRequestMock,
}));

vi.mock('@/lib/supabase', () => ({
  createServerClient: createServerClientMock,
}));

vi.mock('@/lib/spring/memory-v3/service', () => ({
  createMemoryV3Service: createMemoryV3ServiceMock,
}));

function makeRequest(url: string, options?: RequestInit): NextRequest {
  return new NextRequest(new URL(url, 'https://test.seizn.com'), options);
}

describe('GET /api/spring/memory/edges', () => {
  beforeEach(() => {
    vi.clearAllMocks();

    authenticateRequestMock.mockResolvedValue({
      userId: 'user-1',
      keyId: 'key-1',
      rateLimitHeaders: null,
    });
    isAuthErrorMock.mockReturnValue(false);
    authErrorResponseMock.mockReturnValue(new Response('unauthorized', { status: 401 }));
    logRequestMock.mockResolvedValue(undefined);

    createServerClientMock.mockReturnValue({});
    createMemoryV3ServiceMock.mockReturnValue({
      getEdges: getEdgesMock,
      listNotes: listNotesMock,
    });
  });

  it('filters edges by owned notes using a single batched note query', async () => {
    getEdgesMock.mockResolvedValue([
      {
        id: 'edge-1',
        sourceId: 'note-a',
        targetId: 'note-b',
        type: 'similar',
        weight: 0.9,
        properties: {},
        isAutoGenerated: false,
        createdAt: new Date('2026-01-01T00:00:00.000Z'),
        updatedAt: new Date('2026-01-01T00:00:00.000Z'),
      },
      {
        id: 'edge-2',
        sourceId: 'note-c',
        targetId: 'note-d',
        type: 'similar',
        weight: 0.7,
        properties: {},
        isAutoGenerated: false,
        createdAt: new Date('2026-01-02T00:00:00.000Z'),
        updatedAt: new Date('2026-01-02T00:00:00.000Z'),
      },
    ]);

    listNotesMock.mockResolvedValue({
      notes: [
        { id: 'note-a', userId: 'user-1' },
        { id: 'note-b', userId: 'user-2' },
        { id: 'note-c', userId: 'user-3' },
        { id: 'note-d', userId: 'user-4' },
      ],
      total: 4,
    });

    const { GET } = await import('./route');
    const response = await GET(makeRequest('/api/spring/memory/edges?limit=20&offset=0'));
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(listNotesMock).toHaveBeenCalledTimes(1);

    const firstCall = listNotesMock.mock.calls[0][0] as { ids: string[]; limit: number };
    expect(firstCall.limit).toBe(4);
    expect(firstCall.ids).toEqual(expect.arrayContaining(['note-a', 'note-b', 'note-c', 'note-d']));
    expect(body.edges).toHaveLength(1);
    expect(body.edges[0].id).toBe('edge-1');
  });
});

