/**
 * Memory V3 API - Edges Route
 *
 * GET  /api/spring/memory/edges - Query edges
 * POST /api/spring/memory/edges - Create edge
 */

import { NextRequest, NextResponse } from 'next/server';
import {
  authenticateRequest,
  isAuthError,
  authErrorResponse,
  logRequest,
} from '@/lib/api-auth';
import { ValidationErrors, ServerErrors, NotFoundErrors } from '@/lib/api-error';
import { createServerClient } from '@/lib/supabase';
import { createMemoryV3Service } from '@/lib/spring/memory-v3/service';
import type { EdgeQuery, EdgeType, MemoryEdgeInput } from '@/lib/spring/memory-v3/types';

// =============================================================================
// GET /api/spring/memory/edges - Query Edges
// =============================================================================

export async function GET(request: NextRequest) {
  const startTime = Date.now();

  try {
    // Authenticate request
    const authResult = await authenticateRequest(request);
    if (isAuthError(authResult)) {
      return authErrorResponse(authResult.authError);
    }

    const { userId, keyId, rateLimitHeaders } = authResult;
    const { searchParams } = new URL(request.url);

    // Build edge query
    const query: EdgeQuery = {};

    // Filter by edge IDs
    const ids = searchParams.get('ids');
    if (ids) {
      query.ids = ids.split(',');
    }

    // Filter by source note
    const sourceId = searchParams.get('source_id');
    if (sourceId) {
      query.sourceId = sourceId;
    }

    // Filter by target note
    const targetId = searchParams.get('target_id');
    if (targetId) {
      query.targetId = targetId;
    }

    // Filter by either source or target
    const noteId = searchParams.get('note_id');
    if (noteId) {
      query.noteId = noteId;
    }

    // Filter by edge types
    const types = searchParams.get('types');
    if (types) {
      query.types = types.split(',') as EdgeType[];
    }

    // Filter by minimum weight
    const minWeight = searchParams.get('min_weight');
    if (minWeight) {
      query.minWeight = parseFloat(minWeight);
    }

    // Include auto-generated edges
    const includeAutoGenerated = searchParams.get('include_auto_generated');
    if (includeAutoGenerated !== null) {
      query.includeAutoGenerated = includeAutoGenerated !== 'false';
    }

    // Pagination
    const limit = searchParams.get('limit');
    if (limit) {
      query.limit = Math.min(parseInt(limit, 10), 100);
    }

    const offset = searchParams.get('offset');
    if (offset) {
      query.offset = parseInt(offset, 10);
    }

    // Get edges
    const supabase = createServerClient();
    const service = createMemoryV3Service(supabase);
    const edges = await service.getEdges(query);

    // Filter edges to only those where user owns at least one of the notes.
    // Batch note lookup to avoid per-edge DB round-trips (N+1 pattern).
    const noteIds = Array.from(new Set(edges.flatMap((edge) => [edge.sourceId, edge.targetId])));
    const { notes } = noteIds.length
      ? await service.listNotes({ ids: noteIds, limit: noteIds.length })
      : { notes: [] };

    const ownedNoteIds = new Set(notes.filter((note) => note.userId === userId).map((note) => note.id));
    const filteredEdges = edges.filter(
      (edge) => ownedNoteIds.has(edge.sourceId) || ownedNoteIds.has(edge.targetId)
    );

    // Log request
    await logRequest(
      { userId, keyId, endpoint: '/api/spring/memory/edges', method: 'GET', startTime },
      200
    );

    // Build response
    const response = NextResponse.json(
      {
        success: true,
        edges: filteredEdges.map((e) => ({
          id: e.id,
          sourceId: e.sourceId,
          targetId: e.targetId,
          type: e.type,
          weight: e.weight,
          properties: e.properties,
          isAutoGenerated: e.isAutoGenerated,
          createdAt: e.createdAt.toISOString(),
          updatedAt: e.updatedAt.toISOString(),
        })),
        total: filteredEdges.length,
        limit: query.limit || 100,
        offset: query.offset || 0,
      },
      { status: 200 }
    );

    // Add rate limit headers
    if (rateLimitHeaders) {
      Object.entries(rateLimitHeaders).forEach(([k, v]) => response.headers.set(k, v));
    }

    return response;
  } catch (error) {
    console.error('Memory V3 GET edges error:', error);
    return ServerErrors.internal('query_edges');
  }
}

// =============================================================================
// POST /api/spring/memory/edges - Create Edge
// =============================================================================

export async function POST(request: NextRequest) {
  const startTime = Date.now();

  try {
    // Authenticate request
    const authResult = await authenticateRequest(request);
    if (isAuthError(authResult)) {
      return authErrorResponse(authResult.authError);
    }

    const { userId, keyId, rateLimitHeaders } = authResult;

    // Parse request body
    let body: Record<string, unknown>;
    try {
      body = await request.json();
    } catch {
      return ValidationErrors.invalidBody('Invalid JSON');
    }

    // Validate required fields
    const sourceId = body.source_id as string;
    if (!sourceId) {
      return ValidationErrors.missingField('source_id');
    }

    const targetId = body.target_id as string;
    if (!targetId) {
      return ValidationErrors.missingField('target_id');
    }

    const type = body.type as EdgeType;
    if (!type) {
      return ValidationErrors.missingField('type');
    }

    const validTypes: EdgeType[] = ['similar', 'supersedes', 'contradicts', 'derived_from', 'mentions_entity', 'part_of_cluster'];
    if (!validTypes.includes(type)) {
      return ValidationErrors.invalidValue('type', type, validTypes.join(', '));
    }

    // Verify both notes exist and user owns at least one
    const supabase = createServerClient();
    const service = createMemoryV3Service(supabase);

    const sourceNote = await service.getNote(sourceId);
    if (!sourceNote) {
      return NotFoundErrors.memory(sourceId);
    }

    const targetNote = await service.getNote(targetId);
    if (!targetNote) {
      return NotFoundErrors.memory(targetId);
    }

    // Verify ownership of at least one note
    if (sourceNote.userId !== userId && targetNote.userId !== userId) {
      return NextResponse.json(
        {
          success: false,
          error: {
            code: 'FORBIDDEN',
            message: 'You must own at least one of the notes to create an edge',
          },
        },
        { status: 403 }
      );
    }

    // Validate weight if provided
    const weight = body.weight as number | undefined;
    if (weight !== undefined && (typeof weight !== 'number' || weight < 0 || weight > 1)) {
      return ValidationErrors.invalidField('weight', 'must be a number between 0 and 1');
    }

    // Build edge input
    const edgeInput: MemoryEdgeInput = {
      sourceId,
      targetId,
      type,
      weight: weight ?? 1.0,
      properties: body.properties as Record<string, unknown> | undefined,
      isAutoGenerated: body.is_auto_generated === true,
    };

    // Create edge
    const edge = await service.createEdge(edgeInput);

    // Log request
    await logRequest(
      { userId, keyId, endpoint: '/api/spring/memory/edges', method: 'POST', startTime },
      201
    );

    // Build response
    const response = NextResponse.json(
      {
        success: true,
        edge: {
          id: edge.id,
          sourceId: edge.sourceId,
          targetId: edge.targetId,
          type: edge.type,
          weight: edge.weight,
          properties: edge.properties,
          isAutoGenerated: edge.isAutoGenerated,
          createdAt: edge.createdAt.toISOString(),
          updatedAt: edge.updatedAt.toISOString(),
        },
      },
      { status: 201 }
    );

    // Add rate limit headers
    if (rateLimitHeaders) {
      Object.entries(rateLimitHeaders).forEach(([k, v]) => response.headers.set(k, v));
    }

    return response;
  } catch (error) {
    console.error('Memory V3 POST edge error:', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    if (message.includes('not found')) {
      return NotFoundErrors.resource('Note', message);
    }
    return ServerErrors.internal('create_edge');
  }
}

// =============================================================================
// DELETE /api/spring/memory/edges - Delete Edge (by query param)
// =============================================================================

export async function DELETE(request: NextRequest) {
  const startTime = Date.now();

  try {
    // Authenticate request
    const authResult = await authenticateRequest(request);
    if (isAuthError(authResult)) {
      return authErrorResponse(authResult.authError);
    }

    const { userId, keyId, rateLimitHeaders } = authResult;
    const { searchParams } = new URL(request.url);

    // Get edge ID
    const edgeId = searchParams.get('id');
    if (!edgeId) {
      return ValidationErrors.missingField('id (query parameter)');
    }

    // Get the edge first
    const supabase = createServerClient();
    const service = createMemoryV3Service(supabase);
    const edges = await service.getEdges({ ids: [edgeId] });

    if (edges.length === 0) {
      return NotFoundErrors.resource('Edge', edgeId);
    }

    const edge = edges[0];

    // Verify ownership of at least one connected note
    const sourceNote = await service.getNote(edge.sourceId);
    const targetNote = await service.getNote(edge.targetId);

    if (
      (!sourceNote || sourceNote.userId !== userId) &&
      (!targetNote || targetNote.userId !== userId)
    ) {
      return NextResponse.json(
        {
          success: false,
          error: {
            code: 'FORBIDDEN',
            message: 'You must own at least one of the connected notes to delete this edge',
          },
        },
        { status: 403 }
      );
    }

    // Delete the edge
    await service.deleteEdge(edgeId);

    // Log request
    await logRequest(
      { userId, keyId, endpoint: '/api/spring/memory/edges', method: 'DELETE', startTime },
      200
    );

    // Build response
    const response = NextResponse.json(
      {
        success: true,
        deleted: true,
        edgeId,
      },
      { status: 200 }
    );

    // Add rate limit headers
    if (rateLimitHeaders) {
      Object.entries(rateLimitHeaders).forEach(([k, v]) => response.headers.set(k, v));
    }

    return response;
  } catch (error) {
    console.error('Memory V3 DELETE edge error:', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    if (message.includes('not found')) {
      return NotFoundErrors.resource('Edge', message);
    }
    return ServerErrors.internal('delete_edge');
  }
}
