import type {
  CharacterDetail,
  CharacterSummary,
  ConflictItem,
  GraphEdge,
  GraphNode,
  InboxRowDetail,
} from './types';

const characters: CharacterSummary[] = [
  {
    id: 'seoyun',
    name: 'Seoyun',
    aka: 'City reporter',
    role: 'Lead',
    episodes: 7,
    relations: 8,
    conflicts: 2,
    color: '#c96442',
  },
  {
    id: 'doyoon',
    name: 'Doyoon',
    aka: 'Major crimes detective',
    role: 'Lead',
    episodes: 7,
    relations: 6,
    conflicts: 2,
    color: '#7a5c3a',
  },
  {
    id: 'jin',
    name: 'Jin',
    aka: 'Editor-in-chief',
    role: 'Supporting',
    episodes: 5,
    relations: 4,
    conflicts: 0,
    color: '#8a6818',
  },
  {
    id: 'minho',
    name: 'Minho',
    aka: "Seoyun's brother",
    role: 'Supporting',
    episodes: 6,
    relations: 5,
    conflicts: 1,
    color: '#4a4338',
  },
  {
    id: 'yeonsu',
    name: 'Yeonsu',
    aka: "Doyoon's partner",
    role: 'Supporting',
    episodes: 4,
    relations: 3,
    conflicts: 0,
    color: '#a94e2f',
  },
  {
    id: 'mother',
    name: 'Mrs. Han',
    aka: "Yeonsu's mother",
    role: 'Minor',
    episodes: 1,
    relations: 1,
    conflicts: 1,
    color: '#bfb39a',
  },
  {
    id: 'sunwoo',
    name: 'Sunwoo',
    aka: 'Anonymous source',
    role: 'Minor',
    episodes: 2,
    relations: 2,
    conflicts: 0,
    color: '#948872',
  },
];

const characterDetails: CharacterDetail[] = [
  {
    ...characters[0],
    canonFacts: [
      { ep: 'Ch. 1', text: 'Reporter at the Midnight Daily.' },
      { ep: 'Ch. 2', text: 'Younger brother, Minho, lives with her.' },
      { ep: 'Ch. 4', text: 'Three years on the precinct beat.' },
      { ep: 'Ch. 7', text: 'Identifies herself as a detective.', warn: true },
    ],
    relationships: [
      { toId: 'doyoon', name: 'Doyoon', kind: 'Trust', conflict: true, color: '#7a5c3a' },
      { toId: 'jin', name: 'Jin', kind: 'Mentor', conflict: false, color: '#8a6818' },
      { toId: 'minho', name: 'Minho', kind: 'Family', conflict: false, color: '#4a4338' },
    ],
  },
  {
    ...characters[1],
    canonFacts: [
      { ep: 'Ch. 1', text: 'Major crimes detective in the Midnight precinct.' },
      { ep: 'Ch. 3', text: 'Partnered with Yeonsu for two years.' },
      { ep: 'Ch. 6', text: 'Reconciles with Seoyun after 18 months apart.' },
    ],
    relationships: [
      { toId: 'seoyun', name: 'Seoyun', kind: 'Trust', conflict: true, color: '#c96442' },
      { toId: 'yeonsu', name: 'Yeonsu', kind: 'Partner', conflict: false, color: '#a94e2f' },
      { toId: 'minho', name: 'Minho', kind: 'Rivalry', conflict: true, color: '#4a4338' },
    ],
  },
];

const graphNodes: GraphNode[] = [
  { id: 'seoyun', x: 140, y: 140, r: 36, label: 'Seoyun', role: 'Lead' },
  { id: 'doyoon', x: 340, y: 120, r: 34, label: 'Doyoon', role: 'Lead' },
  { id: 'jin', x: 70, y: 280, r: 24, label: 'Jin', role: 'Supporting' },
  { id: 'minho', x: 230, y: 270, r: 24, label: 'Minho', role: 'Supporting' },
  { id: 'yeonsu', x: 430, y: 230, r: 22, label: 'Yeonsu', role: 'Supporting' },
  { id: 'mother', x: 500, y: 320, r: 16, label: 'Mrs. Han', role: 'Minor' },
  { id: 'sunwoo', x: 400, y: 30, r: 16, label: 'Sunwoo', role: 'Minor' },
];

const graphEdges: GraphEdge[] = [
  { a: 'seoyun', b: 'doyoon', kind: 'Trust', strength: 0.55, conflict: true },
  { a: 'seoyun', b: 'jin', kind: 'Mentor', strength: 0.85, conflict: false },
  { a: 'seoyun', b: 'minho', kind: 'Family', strength: 0.95, conflict: false },
  { a: 'doyoon', b: 'yeonsu', kind: 'Partner', strength: 0.8, conflict: false },
  { a: 'doyoon', b: 'minho', kind: 'Rivalry', strength: 0.4, conflict: true },
  { a: 'yeonsu', b: 'mother', kind: 'Family', strength: 0.9, conflict: false },
  { a: 'seoyun', b: 'sunwoo', kind: 'Source', strength: 0.6, conflict: false },
];

const inbox: InboxRowDetail[] = [
  {
    id: '1',
    kind: 'Character',
    title: 'Seoyun is a journalist in Ch. 4 but a detective in Ch. 7',
    episode: 'Ch. 7',
    author: 'Memory v3',
    time: '2m ago',
    priority: 'P1',
    unread: true,
    evidence: [
      {
        reference: 'Ch. 4 · §3',
        kind: 'recorded',
        body:
          "Seoyun pulled out her press card. The journalist from the Daily had spent three years covering the precinct.",
        emphasisText: 'The journalist',
      },
      {
        reference: 'Ch. 7 · §1',
        kind: 'conflicting',
        body: 'Detective Seoyun badged the lobby officer and headed for the elevator.',
        emphasisText: 'Detective Seoyun',
      },
    ],
    suggestion: {
      rationale:
        "Update Ch. 7 §1 to 'Reporter Seoyun', or amend Seoyun's canon entry to add a career change between Ch. 4 and Ch. 7.",
      applyAction: 'Apply suggestion',
      openAction: 'Open in Ch. 7',
      notConflictAction: 'Mark not a conflict',
    },
  },
  {
    id: '2',
    kind: 'Conflict',
    title: 'Doyoon and Seoyun trust line — recovery in Ch. 6 lacks setup',
    episode: 'Ch. 7',
    author: 'You',
    time: '12m ago',
    priority: 'P2',
    unread: true,
    evidence: [],
  },
  {
    id: '3',
    kind: 'Canon',
    title: "'Midnight bells' ritual — order conflicts between Ch. 4 and Ch. 6",
    episode: 'Ch. 6',
    author: 'Memory v3',
    time: '1h ago',
    priority: 'P1',
    unread: false,
    evidence: [],
  },
  {
    id: '4',
    kind: 'Timeline',
    title: 'Minho recovery: 12 days in draft, but medical reference says 4 to 6 weeks',
    episode: 'Ch. 5',
    author: 'Editor Jin',
    time: '3h ago',
    priority: 'P2',
    unread: false,
    evidence: [],
  },
  {
    id: '5',
    kind: 'Character',
    title: "Yeonsu's mother appears — she was set as 'absent' in Ch. 1",
    episode: 'Ch. 8 draft',
    author: 'Memory v3',
    time: 'yesterday',
    priority: 'P1',
    unread: false,
    evidence: [],
  },
  {
    id: '6',
    kind: 'Review',
    title: 'Tone consistency check on Jin and Seoyun flashback',
    episode: 'Ch. 7',
    author: 'Editor Jin',
    time: 'yesterday',
    priority: 'P3',
    unread: false,
    evidence: [],
  },
  {
    id: '7',
    kind: 'Note',
    title: 'Ch. 8 opener candidate — Seoyun-POV prologue',
    episode: 'Ch. 8 draft',
    author: 'You',
    time: '2 days ago',
    priority: 'P3',
    unread: false,
    evidence: [],
  },
];

const conflicts: ConflictItem[] = [
  {
    id: 'c1',
    severity: 'P1',
    kind: 'Character',
    episode: 'Ch. 7',
    title: "Seoyun's profession contradicts Ch. 4 canon",
    why:
      'In Ch. 4 §3 Seoyun is established as a reporter. In Ch. 7 §1 she identifies as a detective with no transition recorded.',
    refs: ['canon/seoyun#profession', 'ep4§3', 'ep7§1'],
  },
  {
    id: 'c2',
    severity: 'P2',
    kind: 'Conflict',
    episode: 'Ch. 7',
    title: 'Doyoon and Seoyun trust recovery lacks setup',
    why:
      "Their bond visibly recovers in Ch. 6's closing scene, but the prior friction never resolves on-page.",
    refs: ['ties/doyoon-seoyun', 'ep6§4'],
  },
  {
    id: 'c3',
    severity: 'P1',
    kind: 'Canon',
    episode: 'Ch. 6',
    title: "'Midnight bells' ritual order conflicts between Ch. 4 and Ch. 6",
    why:
      'Ch. 4 places the bells before the speech; Ch. 6 has them after. Pick a canonical sequence.',
    refs: ['canon/rituals#midnight-bells'],
  },
  {
    id: 'c4',
    severity: 'P2',
    kind: 'Timeline',
    episode: 'Ch. 5',
    title: 'Minho recovery: 12 days vs medical reference 4 to 6 weeks',
    why: undefined,
    refs: ['timeline/minho', 'ep5§2'],
  },
  {
    id: 'c5',
    severity: 'P3',
    kind: 'Note',
    episode: 'Ch. 8 draft',
    title: "Mrs. Han's appearance contradicts Ch. 1 absent-mother setup",
    why: undefined,
    refs: ['canon/yeonsu#family'],
  },
];

export const MOCK_AUTHOR_DATA = {
  workspace: {
    name: 'Midnight City',
    plan: 'Studio',
    episodes: 7,
    words: 84_320,
  },
  characters,
  characterDetails,
  graphNodes,
  graphEdges,
  inbox,
  conflicts,
};
