-- SSO/SAML Foundation for Enterprise Authentication
-- Enables organizations to configure SSO providers for their members

-- ============================================
-- SSO Configuration Table
-- ============================================

-- SSO connection types
CREATE TYPE sso_provider_type AS ENUM ('saml', 'oidc');
CREATE TYPE sso_connection_status AS ENUM ('draft', 'testing', 'active', 'disabled');

-- Organization SSO configurations
CREATE TABLE IF NOT EXISTS sso_connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

  -- Connection identity
  name VARCHAR(100) NOT NULL,
  provider_type sso_provider_type NOT NULL DEFAULT 'saml',
  status sso_connection_status NOT NULL DEFAULT 'draft',

  -- SAML Configuration (stored encrypted in production)
  -- These fields are nullable for draft status
  entity_id VARCHAR(500),           -- IdP Entity ID (e.g., https://idp.example.com/saml)
  sso_url VARCHAR(500),             -- IdP SSO URL
  slo_url VARCHAR(500),             -- IdP Single Logout URL (optional)
  certificate TEXT,                 -- IdP X.509 Certificate (PEM format)

  -- OIDC Configuration (alternative to SAML)
  oidc_issuer VARCHAR(500),         -- OIDC Issuer URL
  oidc_client_id VARCHAR(255),      -- OIDC Client ID
  oidc_client_secret_encrypted TEXT, -- OIDC Client Secret (encrypted)

  -- SP (Service Provider) Configuration - generated by Seizn
  sp_entity_id VARCHAR(500),        -- Our SP Entity ID
  sp_acs_url VARCHAR(500),          -- Assertion Consumer Service URL
  sp_metadata_url VARCHAR(500),     -- SP Metadata URL

  -- Domain mapping for automatic SSO routing
  email_domains TEXT[] DEFAULT '{}', -- e.g., ['example.com', 'corp.example.com']

  -- Attribute mapping (IdP attribute -> Seizn attribute)
  attribute_mapping JSONB DEFAULT '{
    "email": "email",
    "firstName": "first_name",
    "lastName": "last_name",
    "displayName": "display_name",
    "groups": "groups"
  }'::jsonb,

  -- Behavior settings
  settings JSONB DEFAULT '{
    "allowIdpInitiated": true,
    "forceAuthn": false,
    "signRequest": true,
    "wantAssertionsSigned": true,
    "nameIdFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
    "authnContextClassRef": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
    "defaultRole": "member",
    "autoProvision": true,
    "jitProvisioning": true
  }'::jsonb,

  -- Audit
  created_by TEXT REFERENCES profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_tested_at TIMESTAMP WITH TIME ZONE,
  last_used_at TIMESTAMP WITH TIME ZONE,

  -- Constraints
  UNIQUE(organization_id, name)
);

-- SSO Domain Verification (prevent domain hijacking)
CREATE TABLE IF NOT EXISTS sso_domain_verifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  domain VARCHAR(255) NOT NULL,

  -- Verification methods
  verification_method VARCHAR(50) NOT NULL DEFAULT 'dns_txt',
  verification_token VARCHAR(255) NOT NULL,
  verified_at TIMESTAMP WITH TIME ZONE,

  -- Status
  is_verified BOOLEAN NOT NULL DEFAULT false,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  -- One verification per domain per org
  UNIQUE(organization_id, domain)
);

-- SSO Sessions (for SAML session tracking)
CREATE TABLE IF NOT EXISTS sso_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  connection_id UUID NOT NULL REFERENCES sso_connections(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  -- SAML session identifiers
  session_index VARCHAR(255),       -- IdP session index
  name_id VARCHAR(500),             -- SAML NameID
  name_id_format VARCHAR(255),      -- NameID format

  -- Session metadata
  idp_session_not_on_or_after TIMESTAMP WITH TIME ZONE,
  attributes JSONB DEFAULT '{}',    -- Raw SAML attributes

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- SSO Login Attempts (for debugging and security)
CREATE TABLE IF NOT EXISTS sso_login_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  connection_id UUID REFERENCES sso_connections(id) ON DELETE SET NULL,
  organization_id UUID REFERENCES organizations(id) ON DELETE SET NULL,

  -- Request details
  request_id VARCHAR(255),          -- SAML AuthnRequest ID
  relay_state TEXT,                 -- Original URL to redirect to

  -- Response details
  response_status VARCHAR(50),      -- 'success', 'error', 'pending'
  error_code VARCHAR(100),
  error_message TEXT,

  -- User info (if successful)
  user_id TEXT REFERENCES profiles(id) ON DELETE SET NULL,
  email VARCHAR(255),

  -- Metadata
  ip_address INET,
  user_agent TEXT,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- Indexes
-- ============================================

CREATE INDEX IF NOT EXISTS idx_sso_connections_org ON sso_connections(organization_id);
CREATE INDEX IF NOT EXISTS idx_sso_connections_status ON sso_connections(status);
CREATE INDEX IF NOT EXISTS idx_sso_connections_domains ON sso_connections USING GIN(email_domains);
CREATE INDEX IF NOT EXISTS idx_sso_domain_verifications_domain ON sso_domain_verifications(domain);
CREATE INDEX IF NOT EXISTS idx_sso_sessions_user ON sso_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sso_sessions_connection ON sso_sessions(connection_id);
CREATE INDEX IF NOT EXISTS idx_sso_login_attempts_org ON sso_login_attempts(organization_id);
CREATE INDEX IF NOT EXISTS idx_sso_login_attempts_created ON sso_login_attempts(created_at DESC);

-- ============================================
-- Row Level Security
-- ============================================

ALTER TABLE sso_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE sso_domain_verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE sso_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sso_login_attempts ENABLE ROW LEVEL SECURITY;

-- SSO Connections: Only org admins can manage
CREATE POLICY "Org admins can manage SSO connections"
  ON sso_connections FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM organization_members om
      WHERE om.organization_id = sso_connections.organization_id
      AND om.user_id = auth.uid()::text
      AND om.role IN ('owner', 'admin')
    )
  );

-- Domain Verifications: Only org admins can manage
CREATE POLICY "Org admins can manage domain verifications"
  ON sso_domain_verifications FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM organization_members om
      WHERE om.organization_id = sso_domain_verifications.organization_id
      AND om.user_id = auth.uid()::text
      AND om.role IN ('owner', 'admin')
    )
  );

-- SSO Sessions: Users can view their own sessions, admins can view all
CREATE POLICY "Users can view their own SSO sessions"
  ON sso_sessions FOR SELECT
  USING (user_id = auth.uid()::text);

CREATE POLICY "Admins can view org SSO sessions"
  ON sso_sessions FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM sso_connections sc
      JOIN organization_members om ON om.organization_id = sc.organization_id
      WHERE sc.id = sso_sessions.connection_id
      AND om.user_id = auth.uid()::text
      AND om.role IN ('owner', 'admin')
    )
  );

-- Login Attempts: Admins can view for their org
CREATE POLICY "Admins can view login attempts"
  ON sso_login_attempts FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM organization_members om
      WHERE om.organization_id = sso_login_attempts.organization_id
      AND om.user_id = auth.uid()::text
      AND om.role IN ('owner', 'admin')
    )
  );

-- ============================================
-- Helper Functions
-- ============================================

-- Find SSO connection by email domain
CREATE OR REPLACE FUNCTION find_sso_connection_by_email(p_email VARCHAR(255))
RETURNS TABLE (
  connection_id UUID,
  organization_id UUID,
  provider_type sso_provider_type,
  sso_url VARCHAR(500)
) AS $$
DECLARE
  v_domain VARCHAR(255);
BEGIN
  -- Extract domain from email
  v_domain := split_part(p_email, '@', 2);

  RETURN QUERY
  SELECT
    sc.id AS connection_id,
    sc.organization_id,
    sc.provider_type,
    sc.sso_url
  FROM sso_connections sc
  JOIN sso_domain_verifications dv ON dv.organization_id = sc.organization_id
  WHERE sc.status = 'active'
    AND dv.domain = v_domain
    AND dv.is_verified = true
    AND v_domain = ANY(sc.email_domains)
  LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Generate SP metadata URL
CREATE OR REPLACE FUNCTION generate_sp_entity_id(p_org_slug VARCHAR(50))
RETURNS VARCHAR(500) AS $$
BEGIN
  RETURN 'https://seizn.com/api/sso/saml/' || p_org_slug || '/metadata';
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Generate ACS URL
CREATE OR REPLACE FUNCTION generate_sp_acs_url(p_org_slug VARCHAR(50))
RETURNS VARCHAR(500) AS $$
BEGIN
  RETURN 'https://seizn.com/api/sso/saml/' || p_org_slug || '/acs';
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Create SSO connection with auto-generated SP config
CREATE OR REPLACE FUNCTION create_sso_connection(
  p_organization_id UUID,
  p_name VARCHAR(100),
  p_provider_type sso_provider_type DEFAULT 'saml',
  p_created_by TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
  v_connection_id UUID;
  v_org_slug VARCHAR(50);
BEGIN
  -- Get org slug for SP URLs
  SELECT slug INTO v_org_slug FROM organizations WHERE id = p_organization_id;

  INSERT INTO sso_connections (
    organization_id,
    name,
    provider_type,
    sp_entity_id,
    sp_acs_url,
    sp_metadata_url,
    created_by
  ) VALUES (
    p_organization_id,
    p_name,
    p_provider_type,
    generate_sp_entity_id(v_org_slug),
    generate_sp_acs_url(v_org_slug),
    generate_sp_entity_id(v_org_slug),
    p_created_by
  )
  RETURNING id INTO v_connection_id;

  RETURN v_connection_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Update timestamps trigger
CREATE OR REPLACE FUNCTION update_sso_connection_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_sso_connection_updated
  BEFORE UPDATE ON sso_connections
  FOR EACH ROW
  EXECUTE FUNCTION update_sso_connection_timestamp();

-- ============================================
-- Add SSO columns to organizations
-- ============================================

ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS sso_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS sso_enforced BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS default_sso_connection_id UUID REFERENCES sso_connections(id);

-- ============================================
-- Comments
-- ============================================

COMMENT ON TABLE sso_connections IS 'SSO/SAML configurations per organization for enterprise authentication';
COMMENT ON TABLE sso_domain_verifications IS 'Domain ownership verification for SSO email domain routing';
COMMENT ON TABLE sso_sessions IS 'Active SSO sessions for single logout support';
COMMENT ON TABLE sso_login_attempts IS 'SSO login attempt logs for security and debugging';

COMMENT ON COLUMN sso_connections.entity_id IS 'Identity Provider Entity ID';
COMMENT ON COLUMN sso_connections.sso_url IS 'Identity Provider SSO URL for redirecting users';
COMMENT ON COLUMN sso_connections.certificate IS 'IdP X.509 Certificate in PEM format for signature verification';
COMMENT ON COLUMN sso_connections.email_domains IS 'Email domains that should use this SSO connection';
COMMENT ON COLUMN sso_connections.attribute_mapping IS 'Mapping from IdP SAML attributes to Seizn user attributes';
