-- =============================================================================
-- Spring Memory v4 Supplement: Beyond Mem0 Features
-- =============================================================================
-- Additional tables and functions from the v4 DB Migration spec:
-- 1. Memory Candidates (review-before-save queue)
-- 2. Memory Edges (graph relationships: supersedes, contradicts, relates_to)
-- 3. Extended columns for spring_memory_notes
-- 4. Delete by filter function
-- 5. Backfill helpers
-- =============================================================================

-- =============================================================================
-- 0. CLEANUP PARTIAL TABLES (if previous run failed midway)
-- =============================================================================
DROP TABLE IF EXISTS spring_memory_candidates CASCADE;
DROP TABLE IF EXISTS spring_memory_edges CASCADE;

-- =============================================================================
-- 1. MEMORY CANDIDATES (Review Queue)
-- =============================================================================
-- Stores memories pending user approval before being committed to main table

CREATE TABLE spring_memory_candidates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
  workspace_id UUID, -- Optional workspace scoping

  -- Scope context
  namespace TEXT NOT NULL DEFAULT 'default',
  scope VARCHAR(20) NOT NULL DEFAULT 'user',
  session_id TEXT,
  agent_id TEXT,

  -- Content
  content TEXT NOT NULL,
  embedding vector(1536),
  note_type VARCHAR(50) NOT NULL DEFAULT 'fact',
  tags TEXT[] DEFAULT '{}',
  categories TEXT[] DEFAULT '{}',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
  confidence NUMERIC(3,2) NOT NULL DEFAULT 0.80,

  -- Review state
  action VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (action IN ('pending', 'accepted', 'rejected', 'redacted', 'merged')),
  reviewer_user_id TEXT REFERENCES profiles(id),
  reviewed_at TIMESTAMPTZ,
  decision_reason TEXT,

  -- If accepted, link to created note
  accepted_note_id UUID REFERENCES spring_memory_notes(id) ON DELETE SET NULL,

  -- Source tracking
  source_type TEXT DEFAULT 'ingestion'
    CHECK (source_type IN ('ingestion', 'extraction', 'import', 'agent', 'mcp')),
  source_id TEXT, -- Job ID, agent ID, etc.

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ -- Auto-reject after expiration
);

-- Indexes for candidate management
CREATE INDEX IF NOT EXISTS idx_candidates_user_action
  ON spring_memory_candidates(user_id, action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_candidates_namespace
  ON spring_memory_candidates(user_id, namespace, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_candidates_pending
  ON spring_memory_candidates(user_id, created_at DESC)
  WHERE action = 'pending';
CREATE INDEX IF NOT EXISTS idx_candidates_expired
  ON spring_memory_candidates(expires_at)
  WHERE action = 'pending' AND expires_at IS NOT NULL;

-- =============================================================================
-- 2. MEMORY EDGES (Graph Relationships)
-- =============================================================================
-- Represents relationships between memories for graph-based recall

CREATE TABLE spring_memory_edges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Edge endpoints
  src_memory_id UUID NOT NULL REFERENCES spring_memory_notes(id) ON DELETE CASCADE,
  dst_memory_id UUID NOT NULL REFERENCES spring_memory_notes(id) ON DELETE CASCADE,

  -- Edge type
  edge_type VARCHAR(30) NOT NULL CHECK (edge_type IN (
    'relates_to',    -- General relationship
    'supports',      -- Provides evidence for
    'contradicts',   -- Conflicts with
    'supersedes',    -- Replaces/updates
    'derived_from',  -- Created from
    'mentions',      -- References
    'part_of',       -- Component of
    'causes',        -- Causal relationship
    'similar_to'     -- High semantic similarity
  )),

  -- Relationship strength
  weight NUMERIC(3,2) NOT NULL DEFAULT 1.00 CHECK (weight >= 0 AND weight <= 1),

  -- Explanation
  reason TEXT,
  confidence NUMERIC(3,2) DEFAULT 0.80,

  -- Source of edge
  created_by TEXT REFERENCES profiles(id),
  created_by_agent TEXT,
  created_by_system BOOLEAN DEFAULT false, -- Auto-generated by consolidation

  -- Audit
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Prevent duplicate edges
  UNIQUE(src_memory_id, dst_memory_id, edge_type)
);

-- Indexes for graph traversal
CREATE INDEX IF NOT EXISTS idx_edges_src ON spring_memory_edges(src_memory_id);
CREATE INDEX IF NOT EXISTS idx_edges_dst ON spring_memory_edges(dst_memory_id);
CREATE INDEX IF NOT EXISTS idx_edges_type ON spring_memory_edges(edge_type);
CREATE INDEX IF NOT EXISTS idx_edges_src_type ON spring_memory_edges(src_memory_id, edge_type);
CREATE INDEX IF NOT EXISTS idx_edges_dst_type ON spring_memory_edges(dst_memory_id, edge_type);

-- =============================================================================
-- 3. EXTENDED COLUMNS FOR spring_memory_notes
-- =============================================================================

-- Add canonical_id for grouped/consolidated memories
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'spring_memory_notes' AND column_name = 'canonical_id'
  ) THEN
    ALTER TABLE spring_memory_notes ADD COLUMN canonical_id UUID;
    COMMENT ON COLUMN spring_memory_notes.canonical_id IS 'Points to the canonical version when memories are consolidated';
  END IF;
END $$;

-- Add superseded_by for version tracking
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'spring_memory_notes' AND column_name = 'superseded_by'
  ) THEN
    ALTER TABLE spring_memory_notes ADD COLUMN superseded_by UUID REFERENCES spring_memory_notes(id);
    COMMENT ON COLUMN spring_memory_notes.superseded_by IS 'Points to the note that supersedes this one';
  END IF;
END $$;

-- Add used_count for usage tracking
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'spring_memory_notes' AND column_name = 'used_count'
  ) THEN
    ALTER TABLE spring_memory_notes ADD COLUMN used_count BIGINT NOT NULL DEFAULT 0;
    COMMENT ON COLUMN spring_memory_notes.used_count IS 'Number of times this memory was retrieved and used';
  END IF;
END $$;

-- Add last_used_at for recency tracking
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'spring_memory_notes' AND column_name = 'last_used_at'
  ) THEN
    ALTER TABLE spring_memory_notes ADD COLUMN last_used_at TIMESTAMPTZ;
    COMMENT ON COLUMN spring_memory_notes.last_used_at IS 'When this memory was last retrieved';
  END IF;
END $$;

-- Add content_hash for deduplication
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'spring_memory_notes' AND column_name = 'content_hash'
  ) THEN
    ALTER TABLE spring_memory_notes ADD COLUMN content_hash TEXT;
    COMMENT ON COLUMN spring_memory_notes.content_hash IS 'SHA256 hash of content for deduplication';
  END IF;
END $$;

-- Add provenance for tracking origin
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'spring_memory_notes' AND column_name = 'provenance'
  ) THEN
    ALTER TABLE spring_memory_notes ADD COLUMN provenance JSONB NOT NULL DEFAULT '{}'::jsonb;
    COMMENT ON COLUMN spring_memory_notes.provenance IS 'Origin tracking: source, method, confidence, etc.';
  END IF;
END $$;

-- Add categories array (in addition to single category)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'spring_memory_notes' AND column_name = 'categories'
  ) THEN
    ALTER TABLE spring_memory_notes ADD COLUMN categories TEXT[] DEFAULT '{}';
    COMMENT ON COLUMN spring_memory_notes.categories IS 'Multiple categories for multi-label classification';
  END IF;
END $$;

-- Indexes for new columns
CREATE INDEX IF NOT EXISTS idx_notes_canonical ON spring_memory_notes(canonical_id) WHERE canonical_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_notes_superseded ON spring_memory_notes(superseded_by) WHERE superseded_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_notes_used_count ON spring_memory_notes(user_id, used_count DESC);
CREATE INDEX IF NOT EXISTS idx_notes_last_used ON spring_memory_notes(user_id, last_used_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_notes_content_hash ON spring_memory_notes(user_id, content_hash) WHERE content_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_notes_categories_gin ON spring_memory_notes USING GIN (categories);

-- =============================================================================
-- 4. CONTENT HASH TRIGGER
-- =============================================================================

CREATE OR REPLACE FUNCTION set_spring_content_hash()
RETURNS TRIGGER AS $$
BEGIN
  NEW.content_hash = encode(digest(COALESCE(NEW.content, ''), 'sha256'), 'hex');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_spring_notes_content_hash') THEN
    CREATE TRIGGER trg_spring_notes_content_hash
    BEFORE INSERT OR UPDATE OF content ON spring_memory_notes
    FOR EACH ROW EXECUTE FUNCTION set_spring_content_hash();
  END IF;
END $$;

-- =============================================================================
-- 5. USAGE TRACKING TRIGGER (updates used_count, last_used_at)
-- =============================================================================

CREATE OR REPLACE FUNCTION bump_spring_memory_usage()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE spring_memory_notes
  SET
    used_count = used_count + 1,
    last_used_at = NEW.created_at
  WHERE id = NEW.note_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_spring_usage_bump') THEN
    CREATE TRIGGER trg_spring_usage_bump
    AFTER INSERT ON spring_memory_usage
    FOR EACH ROW EXECUTE FUNCTION bump_spring_memory_usage();
  END IF;
END $$;

-- =============================================================================
-- 6. DELETE BY FILTER FUNCTION
-- =============================================================================

CREATE OR REPLACE FUNCTION delete_spring_memories_by_filter(
  p_user_id TEXT,
  p_filters JSONB DEFAULT '{}'::jsonb
) RETURNS INT AS $$
DECLARE
  types_filter TEXT[];
  categories_filter TEXT[];
  namespace_filter TEXT;
  before_ts TIMESTAMPTZ;
  after_ts TIMESTAMPTZ;
  affected INT := 0;
BEGIN
  -- Extract filters
  types_filter := ARRAY(SELECT jsonb_array_elements_text(p_filters->'types'));
  categories_filter := ARRAY(SELECT jsonb_array_elements_text(p_filters->'categories'));
  namespace_filter := p_filters->>'namespace';
  before_ts := (p_filters->>'before')::timestamptz;
  after_ts := (p_filters->>'after')::timestamptz;

  -- Soft delete matching memories (v3 compatible)
  UPDATE spring_memory_notes
  SET
    status = 'deleted',
    updated_at = now()
  WHERE user_id = p_user_id
    AND status != 'deleted'
    AND (array_length(types_filter, 1) IS NULL OR note_type = ANY(types_filter))
    AND (array_length(categories_filter, 1) IS NULL OR categories && categories_filter)
    AND (namespace_filter IS NULL OR scope = namespace_filter)
    AND (before_ts IS NULL OR created_at < before_ts)
    AND (after_ts IS NULL OR created_at > after_ts);

  GET DIAGNOSTICS affected = ROW_COUNT;
  RETURN affected;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- 7. GRAPH TRAVERSAL HELPERS
-- =============================================================================

-- Get all edges for a memory (both directions)
CREATE OR REPLACE FUNCTION get_memory_edges(
  p_memory_id UUID,
  p_edge_types TEXT[] DEFAULT NULL,
  p_direction TEXT DEFAULT 'both' -- 'outgoing', 'incoming', 'both'
)
RETURNS TABLE (
  edge_id UUID,
  other_memory_id UUID,
  edge_type VARCHAR(30),
  weight NUMERIC,
  direction TEXT,
  reason TEXT,
  created_at TIMESTAMPTZ
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    e.id,
    CASE WHEN e.src_memory_id = p_memory_id THEN e.dst_memory_id ELSE e.src_memory_id END,
    e.edge_type,
    e.weight,
    CASE WHEN e.src_memory_id = p_memory_id THEN 'outgoing'::text ELSE 'incoming'::text END,
    e.reason,
    e.created_at
  FROM spring_memory_edges e
  WHERE (
    (p_direction = 'both' AND (e.src_memory_id = p_memory_id OR e.dst_memory_id = p_memory_id))
    OR (p_direction = 'outgoing' AND e.src_memory_id = p_memory_id)
    OR (p_direction = 'incoming' AND e.dst_memory_id = p_memory_id)
  )
  AND (p_edge_types IS NULL OR e.edge_type = ANY(p_edge_types))
  ORDER BY e.weight DESC, e.created_at DESC;
END;
$$ LANGUAGE plpgsql STABLE;

-- Get canonical memory (follow supersedes chain)
CREATE OR REPLACE FUNCTION get_canonical_memory(p_memory_id UUID)
RETURNS UUID AS $$
DECLARE
  current_id UUID := p_memory_id;
  next_id UUID;
  iteration INT := 0;
BEGIN
  LOOP
    SELECT superseded_by INTO next_id
    FROM spring_memory_notes
    WHERE id = current_id AND superseded_by IS NOT NULL;

    IF next_id IS NULL THEN
      RETURN current_id;
    END IF;

    current_id := next_id;
    iteration := iteration + 1;

    -- Prevent infinite loops (max 100 hops)
    IF iteration > 100 THEN
      RETURN current_id;
    END IF;
  END LOOP;
END;
$$ LANGUAGE plpgsql STABLE;

-- Find contradicting memories
CREATE OR REPLACE FUNCTION find_contradicting_memories(p_memory_id UUID)
RETURNS TABLE (
  contradicting_id UUID,
  content TEXT,
  reason TEXT,
  confidence NUMERIC
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    n.id,
    n.content,
    e.reason,
    e.confidence
  FROM spring_memory_edges e
  JOIN spring_memory_notes n ON (
    (e.src_memory_id = p_memory_id AND n.id = e.dst_memory_id)
    OR (e.dst_memory_id = p_memory_id AND n.id = e.src_memory_id)
  )
  WHERE e.edge_type = 'contradicts'
    AND n.status = 'active'
    AND n.deleted_at IS NULL
  ORDER BY e.confidence DESC, e.created_at DESC;
END;
$$ LANGUAGE plpgsql STABLE;

-- =============================================================================
-- 8. CANDIDATE MANAGEMENT FUNCTIONS
-- =============================================================================

-- Accept a candidate (move to main table)
CREATE OR REPLACE FUNCTION accept_memory_candidate(
  p_candidate_id UUID,
  p_reviewer_id TEXT,
  p_reason TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
  v_candidate spring_memory_candidates;
  v_note_id UUID;
BEGIN
  -- Get candidate
  SELECT * INTO v_candidate
  FROM spring_memory_candidates
  WHERE id = p_candidate_id AND action = 'pending';

  IF v_candidate.id IS NULL THEN
    RAISE EXCEPTION 'Candidate not found or already processed';
  END IF;

  -- Insert into main table (using v3 column names)
  INSERT INTO spring_memory_notes (
    user_id, workspace_id, content, note_type, status,
    scope, confidence, payload_json, embedding
  )
  VALUES (
    v_candidate.user_id, v_candidate.workspace_id, v_candidate.content,
    v_candidate.note_type, 'active',
    v_candidate.scope, v_candidate.confidence, v_candidate.metadata, v_candidate.embedding
  )
  RETURNING id INTO v_note_id;

  -- Update candidate status
  UPDATE spring_memory_candidates
  SET
    action = 'accepted',
    reviewer_user_id = p_reviewer_id,
    reviewed_at = now(),
    decision_reason = p_reason,
    accepted_note_id = v_note_id
  WHERE id = p_candidate_id;

  RETURN v_note_id;
END;
$$ LANGUAGE plpgsql;

-- Reject a candidate
CREATE OR REPLACE FUNCTION reject_memory_candidate(
  p_candidate_id UUID,
  p_reviewer_id TEXT,
  p_reason TEXT DEFAULT NULL
)
RETURNS BOOLEAN AS $$
BEGIN
  UPDATE spring_memory_candidates
  SET
    action = 'rejected',
    reviewer_user_id = p_reviewer_id,
    reviewed_at = now(),
    decision_reason = p_reason
  WHERE id = p_candidate_id AND action = 'pending';

  RETURN FOUND;
END;
$$ LANGUAGE plpgsql;

-- Batch expire old pending candidates
CREATE OR REPLACE FUNCTION expire_old_candidates(p_older_than INTERVAL DEFAULT '7 days')
RETURNS INT AS $$
DECLARE
  affected INT;
BEGIN
  UPDATE spring_memory_candidates
  SET
    action = 'rejected',
    decision_reason = 'Auto-expired after ' || p_older_than::text
  WHERE action = 'pending'
    AND (
      (expires_at IS NOT NULL AND expires_at < now())
      OR (expires_at IS NULL AND created_at < now() - p_older_than)
    );

  GET DIAGNOSTICS affected = ROW_COUNT;
  RETURN affected;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- 9. RLS POLICIES FOR NEW TABLES
-- =============================================================================

ALTER TABLE spring_memory_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE spring_memory_edges ENABLE ROW LEVEL SECURITY;

-- Candidates policies
CREATE POLICY "Users can view their own candidates"
  ON spring_memory_candidates FOR SELECT
  USING (user_id = auth.uid()::text);

CREATE POLICY "Users can manage their own candidates"
  ON spring_memory_candidates FOR ALL
  USING (user_id = auth.uid()::text);

-- Edges policies (through memory ownership)
CREATE POLICY "Users can view edges for their memories"
  ON spring_memory_edges FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM spring_memory_notes n
      WHERE n.id = src_memory_id AND n.user_id = auth.uid()::text
    )
    OR EXISTS (
      SELECT 1 FROM spring_memory_notes n
      WHERE n.id = dst_memory_id AND n.user_id = auth.uid()::text
    )
  );

CREATE POLICY "Users can create edges for their memories"
  ON spring_memory_edges FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM spring_memory_notes n
      WHERE n.id = src_memory_id AND n.user_id = auth.uid()::text
    )
  );

CREATE POLICY "Users can delete edges for their memories"
  ON spring_memory_edges FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM spring_memory_notes n
      WHERE n.id = src_memory_id AND n.user_id = auth.uid()::text
    )
  );

-- =============================================================================
-- 10. BACKFILL CONTENT HASH FOR EXISTING NOTES
-- =============================================================================

-- Run this separately if you have existing data
-- UPDATE spring_memory_notes
-- SET content_hash = encode(digest(COALESCE(content, ''), 'sha256'), 'hex')
-- WHERE content_hash IS NULL;
